# Fly emir project Python package

package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "fly_emir_project_py",
    srcs = glob(["*.py"]),
    deps = [
        "//src/fly:fly_py",  # project.py: Project base / UserDoc / Schema
    ],
)
