# Fly common types tests

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "common_types_test",
    srcs = ["common_types_test.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "//src/common/cpp:fly_common_types",
    ],
    copts = ["-std=c++20"],
)