package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "project_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/emir/project/py:fly_emir_project_py"],
)
