package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "test_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/test/py:fly_test_py"],
)
