package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "container_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/container/py:fly_container_py"],
)
