#!/usr/bin/env bash
# Fly build script - builds and auto-updates compile_commands.json for clangd.
# Run this instead of raw `bazel build` to keep clangd working after adding new files.
#
# Usage:
#   ./fly.sh build [target...]      - Build + refresh clangd (default)
#   ./fly.sh test [target...]      - Test + refresh clangd
#   ./fly.sh buildonly [target...] - Build only, no clangd refresh
#   ./fly.sh refresh               - Refresh compile_commands.json only
#   ./fly.sh check                 - Build, test, and refresh clangd
#   ./fly.sh install               - Create build/ with symlinks
set -euo pipefail

FLY_ROOT="$(cd "$(dirname "$0")" && pwd)"
DEFAULT_BUILD_TARGETS="//src/..."
DEFAULT_TEST_TARGETS="//src/..."

# Respect .bazelversion if present
if [ -f "$FLY_ROOT/.bazelversion" ]; then
    export USE_BAZEL_VERSION="$(cat "$FLY_ROOT/.bazelversion")"
fi

# Python path auto-detection
# Generates .bazelrc.user with machine-specific Python 3.12 include/link paths.
# Different machines may have Python 3.12 headers at /usr/include or /usr/local/include.
detect_python_paths() {
    local python_exe="python3.12"
    if ! command -v "$python_exe" &>/dev/null; then
        echo "ERROR: $python_exe not found. Please install Python 3.12." >&2
        exit 1
    fi

    local user_rc="$FLY_ROOT/.bazelrc.user"
    local include_path lib_dir

    include_path=$($python_exe -c "import sysconfig; print(sysconfig.get_path('include'))")
    lib_dir=$($python_exe -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")

    # Validate paths exist
    if [ ! -f "$include_path/Python.h" ]; then
        echo "ERROR: Python.h not found at $include_path" >&2
        echo "Install python3.12-dev or equivalent for your system." >&2
        exit 1
    fi

    cat > "$user_rc" <<EOF
# AUTO-GENERATED by fly.sh - do not edit manually
# Python 3.12 paths detected on $(hostname) at $(date -Iseconds)
build --copt=-I${include_path}
build --host_cxxopt=-I${include_path}
build --linkopt=-L${lib_dir}
build --linkopt=-lpython3.12
EOF
    echo ">>> Python 3.12: include=${include_path}, lib=${lib_dir}"
}

refresh_clangd() {
    echo ">>> Refreshing compile_commands.json for clangd..."
    cd "$FLY_ROOT"

    local all_targets
    all_targets=$(bazel query "kind('cc_library|cc_binary|cc_test', //src/...)" 2>/dev/null | sort -u)

    if [ -z "$all_targets" ]; then
        echo "WARNING: No targets discovered. Building first..."
        bazel build $DEFAULT_BUILD_TARGETS 2>/dev/null || true
        all_targets=$(bazel query "kind('cc_library|cc_binary|cc_test', //src/...)" 2>/dev/null | sort -u)
    fi

    local count
    count=$(echo "$all_targets" | wc -w)
    echo ">>> Found $count targets for clangd"

    # Use local refresh tool (no Bazel target needed - avoids native.py_binary issue with Bazel 9)
    python3 "$FLY_ROOT/tools/refresh_compile_commands/refresh.py" \
        --targets $all_targets \
        --output "$FLY_ROOT/compile_commands.json" 2>&1 || {
        echo "WARNING: clangd refresh failed (non-fatal)" >&2
    }

    echo ">>> compile_commands.json updated ($count targets)"
}

do_install() {
    cd "$FLY_ROOT"
    local build_dir="$FLY_ROOT/build"
    local bazel_bin="$FLY_ROOT/bazel-bin"

    if [ ! -d "$bazel_bin/src" ]; then
        echo "ERROR: bazel-bin not found. Run './fly.sh build' first." >&2
        exit 1
    fi

    echo ">>> Installing to $build_dir/"
    rm -rf "$build_dir"
    mkdir -p "$build_dir/bin" "$build_dir/lib"
    mkdir -p "$build_dir/python/fly"
    mkdir -p "$build_dir/python/core"
    mkdir -p "$build_dir/python/storage"
    mkdir -p "$build_dir/python/agent"
    mkdir -p "$build_dir/python/log"
    mkdir -p "$build_dir/python/network"
    mkdir -p "$build_dir/python/task"
    mkdir -p "$build_dir/python/test"
    mkdir -p "$build_dir/python/solver"

    # Binary + wrapper script
    ln -sf "$bazel_bin/src/main/cpp/fly" "$build_dir/bin/fly.bin"
    cat > "$build_dir/bin/fly" <<'WRAPPER'
#!/usr/bin/env bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="$(dirname "$SCRIPT_DIR")"
export FLY_BUILD="$BUILD_DIR"
export LD_LIBRARY_PATH="$BUILD_DIR/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
export PYTHONPATH="$BUILD_DIR/lib:$BUILD_DIR/python${PYTHONPATH:+:$PYTHONPATH}"
exec "$SCRIPT_DIR/fly.bin" "$@"
WRAPPER
    chmod +x "$build_dir/bin/fly"

    # C++ shared libs (export .so + lib*_so.so dependencies)
    for so in "$bazel_bin"/src/*/export/_fly_*.so; do
        [ -f "$so" ] && ln -sf "$so" "$build_dir/lib/"
    done
    for so in "$bazel_bin"/src/*/cpp/libfly_*_so.so; do
        [ -f "$so" ] && ln -sf "$so" "$build_dir/lib/"
    done

    # Python modules: .so files + Python source
    for mod in core log network task test; do
        local so="$bazel_bin/src/$mod/export/_fly_${mod}.so"
        [ -f "$so" ] && ln -sf "$so" "$build_dir/python/$mod/"
        for py in "$FLY_ROOT/src/$mod/py/"*.py; do
            [ -f "$py" ] && ln -sf "$py" "$build_dir/python/$mod/"
        done
    done

    # Storage (has extra _fly_storage.so naming)
    ln -sf "$bazel_bin/src/storage/export/_fly_storage.so" "$build_dir/python/storage/"
    for py in "$FLY_ROOT/src/storage/py/"*.py; do
        [ -f "$py" ] && ln -sf "$py" "$build_dir/python/storage/"
    done

    # Agent
    ln -sf "$bazel_bin/src/agent/export/_fly_agent.so" "$build_dir/python/agent/"
    for py in "$FLY_ROOT/src/agent/py/"*.py; do
        [ -f "$py" ] && ln -sf "$py" "$build_dir/python/agent/"
    done

    # Solver
    ln -sf "$bazel_bin/src/solver/export/_fly_solver.so" "$build_dir/python/solver/"
    for py in "$FLY_ROOT/src/solver/py/"*.py; do
        [ -f "$py" ] && ln -sf "$py" "$build_dir/python/solver/"
    done

    # fly package
    for py in "$FLY_ROOT/src/fly/"*.py; do
        [ -f "$py" ] && ln -sf "$py" "$build_dir/python/fly/"
    done

    # Third-party Python packages (cloudpickle/numpy/scipy) from bazel @pip hub.
    #
    # Production `fly` embeds libpython and imports these packages at runtime.
    # Unlike the .so bindings above, the @pip wheels are NOT bazel runfiles for
    # the cc_binary, so we copy them into a standard site-packages layout that
    # setup_sys_path() in main.cpp adds to sys.path. This makes the installed
    # binary hermetic — it no longer reads cloudpickle/numpy/scipy from the
    # system site-packages.
    #
    # pytest is intentionally NOT copied: it is a test-only dep consumed by
    # py_test targets in the bazel sandbox, never imported by production fly.
    #
    # We copy (not symlink) the unpacked wheel tree because (1) wheels unpack
    # to multi-file directory trees, (2) bazel's external repos may be evicted
    # by `bazel clean`/disk pressure, breaking symlinks, and (3) scipy bundles
    # native .so libraries in scipy.libs/ whose permissions must be preserved.
    local pip_site="$build_dir/python/lib/python3.12/site-packages"
    mkdir -p "$pip_site"
    local output_base
    output_base="$(bazel --nohome_rc info output_base 2>/dev/null)"
    local pkg repo_root build_file_path
    for pkg in cloudpickle numpy scipy; do
        # Resolve the wheel's extracted repo root via cquery. The
        # :extracted_whl_files target emits a BUILD.bazel at the repo root;
        # we parse its path to locate site-packages/ without hardcoding the
        # internal "rules_python++pip+pip_312_<pkg>" repo-name string.
        build_file_path="$(bazel --nohome_rc cquery "@pip//$pkg:extracted_whl_files" \
            --output=starlark \
            --starlark:expr='str([f.path for f in target.files.to_list() if f.basename == "BUILD.bazel"][0])' \
            2>/dev/null)"
        if [ -z "$build_file_path" ]; then
            echo "ERROR: failed to resolve @pip//$pkg wheel layout" >&2
            exit 1
        fi
        repo_root="$(dirname "$output_base/$build_file_path")"
        if [ ! -d "$repo_root/site-packages" ]; then
            echo "ERROR: $pkg site-packages not found at $repo_root/site-packages" >&2
            exit 1
        fi
        # "site-packages/." merges the unpacked wheel contents (package dir +
        # .dist-info) into our combined site-packages root.
        cp -r "$repo_root/site-packages/." "$pip_site/"
    done

    echo ">>> Install complete: $build_dir/bin/fly"
}

case "${1:-build}" in
    build)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Building: $targets"
        bazel build $targets
        refresh_clangd
        echo ">>> Build complete. clangd index updated."
        ;;
    test)
        shift || true
        targets="${@:-$DEFAULT_TEST_TARGETS}"
        detect_python_paths
        echo ">>> Testing: $targets"
        bazel test $targets --test_output=errors
        echo ">>> Tests complete."
        ;;
    buildonly)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Building (no clangd refresh): $targets"
        bazel build $targets
        ;;
    refresh)
        refresh_clangd
        echo ">>> clangd index refreshed."
        ;;
    check)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Quick check: $targets"
        bazel build $targets
        local test_output
        test_output=$(bazel test //src/... --test_output=errors 2>&1)
        local test_exit=$?
        echo "$test_output" | tail -20
        if [ $test_exit -ne 0 ]; then
            echo ">>> TESTS FAILED (exit code: $test_exit)"
            return $test_exit
        fi
        refresh_clangd
        echo ">>> Check complete."
        ;;
    install)
        do_install
        ;;
    *)
        echo "Usage: $0 {build|test|buildonly|refresh|check|install} [target...]"
        echo ""
        echo "  build      Build + refresh clangd (default)"
        echo "  test       Run tests (no clangd refresh)"
        echo "  buildonly  Build without refreshing clangd"
        echo "  refresh    Only refresh compile_commands.json"
        echo "  check      Build, test, and refresh clangd"
        echo "  install    Create build/ with symlinks to bazel-bin artifacts"
        exit 1
        ;;
esac
