#!/usr/bin/env bash
# Fly build script - builds and auto-updates compile_commands.json for clangd.
# Run this instead of raw `bazel build` to keep clangd working after adding new files.
#
# Usage:
#   ./fly.sh build [target...]      - Build + refresh clangd (default)
#   ./fly.sh test [target...]      - Test + refresh clangd
#   ./fly.sh buildonly [target...] - Build only, no clangd refresh
#   ./fly.sh refresh               - Refresh compile_commands.json only
#   ./fly.sh check                 - Build, test, and refresh clangd
set -euo pipefail

FLY_ROOT="$(cd "$(dirname "$0")" && pwd)"
BUILD_FILE="$FLY_ROOT/BUILD"
DEFAULT_BUILD_TARGETS="//src/..."
DEFAULT_TEST_TARGETS="//src/..."

# Python path auto-detection
# Generates .bazelrc.user with machine-specific Python 3.12 include/link paths.
# Different machines may have Python 3.12 headers at /usr/include or /usr/local/include.
detect_python_paths() {
    local python_exe="python3.12"
    if ! command -v "$python_exe" &>/dev/null; then
        echo "ERROR: $python_exe not found. Please install Python 3.12." >&2
        exit 1
    fi

    local user_rc="$FLY_ROOT/.bazelrc.user"
    local include_path lib_dir

    include_path=$($python_exe -c "import sysconfig; print(sysconfig.get_path('include'))")
    lib_dir=$($python_exe -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")

    # Validate paths exist
    if [ ! -f "$include_path/Python.h" ]; then
        echo "ERROR: Python.h not found at $include_path" >&2
        echo "Install python3.12-dev or equivalent for your system." >&2
        exit 1
    fi

    cat > "$user_rc" <<EOF
# AUTO-GENERATED by fly.sh - do not edit manually
# Python 3.12 paths detected on $(hostname) at $(date -Iseconds)
build --copt=-I${include_path}
build --host_cxxopt=-I${include_path}
build --linkopt=-L${lib_dir}
build --linkopt=-lpython3.12
EOF
    echo ">>> Python 3.12: include=${include_path}, lib=${lib_dir}"
}

refresh_clangd() {
    echo ">>> Refreshing compile_commands.json for clangd..."
    cd "$FLY_ROOT"

    local all_targets
    all_targets=$(bazel query "kind('cc_library|cc_binary|cc_test', //src/...)" 2>/dev/null | sort -u)

    if [ -z "$all_targets" ]; then
        echo "WARNING: No targets discovered. Building first..."
        bazel build $DEFAULT_BUILD_TARGETS 2>/dev/null || true
        all_targets=$(bazel query "kind('cc_library|cc_binary|cc_test', //src/...)" 2>/dev/null | sort -u)
    fi

    local valid_targets=""
    for target in $all_targets; do
        valid_targets="$valid_targets $target"
    done

    local count
    count=$(echo "$valid_targets" | wc -w)
    echo ">>> Found $count targets for clangd"

    {
        echo "# Top-level BUILD for Fly project"
        echo "# AUTO-GENERATED by fly.sh - do not edit manually"
        echo ""
        echo "package(default_visibility = [\"//visibility:public\"])"
        echo ""
        echo "load(\"@hedron_compile_commands//:refresh_compile_commands.bzl\", \"refresh_compile_commands\")"
        echo ""
        echo "refresh_compile_commands("
        echo "    name = \"refresh_compile_commands\","
        echo "    targets = {"
        for target in $valid_targets; do
            echo "        \"${target}\": \"\","
        done
        echo "    },"
        echo ")"
    } > "$BUILD_FILE"

    bazel run //:refresh_compile_commands 2>&1 | tail -5 || true

    echo ">>> compile_commands.json updated ($count targets)"
}

case "${1:-build}" in
    build)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Building: $targets"
        bazel build $targets
        refresh_clangd
        echo ">>> Build complete. clangd index updated."
        ;;
    test)
        shift || true
        targets="${@:-$DEFAULT_TEST_TARGETS}"
        detect_python_paths
        echo ">>> Testing: $targets"
        bazel test $targets --test_output=errors
        refresh_clangd
        echo ">>> Tests complete. clangd index updated."
        ;;
    buildonly)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Building (no clangd refresh): $targets"
        bazel build $targets
        ;;
    refresh)
        refresh_clangd
        echo ">>> clangd index refreshed."
        ;;
    check)
        shift || true
        targets="${@:-$DEFAULT_BUILD_TARGETS}"
        detect_python_paths
        echo ">>> Quick check: $targets"
        bazel build $targets
        bazel test //src/... --test_output=errors 2>&1 | tail -20
        refresh_clangd
        echo ">>> Check complete."
        ;;
    *)
        echo "Usage: $0 {build|test|buildonly|refresh|check} [target...]"
        echo ""
        echo "  build      Build + refresh clangd (default)"
        echo "  test       Run tests + refresh clangd"
        echo "  buildonly  Build without refreshing clangd"
        echo "  refresh    Only refresh compile_commands.json"
        echo "  check      Build, test, and refresh clangd"
        exit 1
        ;;
esac
