package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "lib_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/emir/lib/py:fly_emir_lib_py"],
)
