package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "task_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/task/py:fly_task_py"],
)
