package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "agent_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/agent/py:fly_agent_py"],
)
