package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "solver_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/solver/py:fly_solver_py"],
)
