package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "core_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/core/py:fly_core_py"],
)
