package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "storage_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/storage/py:fly_storage_py"],
)
