package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "emir_pkg",
    srcs = ["__init__.py"],
    deps = [
        "//src/emir/lib:lib_pkg",
        "//src/emir/project:project_pkg",
    ],
)
