# Fly storage Python package

package(default_visibility = ["//visibility:public"])

py_library(
    name = "fly_storage_py",
    srcs = [
        "__init__.py",
        "database.py",
    ],
    deps = ["//src/storage/export:_fly_storage.so"],
)