# Fly storage module tests

package(default_visibility = ["//visibility:public"])

load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "object_cache_test",
    srcs = ["object_cache_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "compressor_test",
    srcs = ["compressor_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "storage_basics_test",
    srcs = ["storage_basics_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "local_index_test",
    srcs = ["local_index_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "data_writer_test",
    srcs = ["data_writer_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "data_reader_test",
    srcs = ["data_reader_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "database_test",
    srcs = ["database_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "storage_manager_test",
    srcs = ["storage_manager_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "data_service_test",
    srcs = ["data_service_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "write_registration_test",
    srcs = ["write_registration_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "write_back_queue_test",
    srcs = ["write_back_queue_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "write_context_hash_test",
    srcs = ["write_context_hash_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "compressing_streambuf_test",
    srcs = ["compressing_streambuf_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)

cc_test(
    name = "temp_store_test",
    srcs = ["temp_store_test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/storage/cpp:fly_storage",
    ],
    copts = ["-std=c++20"],
)
