# Fly emir common Python package（纯 Python 基座，无 .so 依赖）

package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "fly_emir_common_py",
    srcs = glob(["*.py"]),
)
