package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "fly_network_py",
    srcs = ["__init__.py"],
    deps = [],
    visibility = ["//visibility:public"],
)