package(default_visibility = ["//visibility:public"])

load("@rules_python//python:defs.bzl", "py_library")

py_library(
    name = "network_pkg",
    srcs = ["__init__.py"],
    deps = ["//src/network/py:fly_network_py"],
)
